# ==============================================================================
# NOTE: THIS SCRIPT WAS GENERATED BY AN LLM (LARGE LANGUAGE MODEL).
# ==============================================================================

import logging
import os
from pathlib import Path
from garminconnect import (
    Garmin,
    GarminConnectAuthenticationError,
    GarminConnectTooManyRequestsError,
)
import matplotlib.pyplot as plt
import pandas as pd

# Configure logging
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


def initialize_garmin_client() -> Garmin:
    """Initializes and authenticates the Garmin Connect API client."""
    token_store = Path.home() / ".garminconnect"

    try:
        logger.info(
            f"Attempting to login using stored tokens from {token_store}..."
        )
        client = Garmin()
        client.login(token_store)
        return client
    except Exception:
        logger.info(
            "Stored tokens invalid or not found. Falling back to environment"
            " variables..."
        )

    email = os.getenv("GARMIN_EMAIL")
    password = os.getenv("GARMIN_PASSWORD")

    if not email or not password:
        raise ValueError(
            "Missing GARMIN_EMAIL or GARMIN_PASSWORD environment variables."
        )

    client = Garmin(email=email, password=password)
    client.login(token_store)
    return client


def get_combined_runs_dataset() -> pd.DataFrame:
    """Fetches activity splits for all runs and extracts relevant lap metrics,

    skipping activities missing required columns.
    """
    client = initialize_garmin_client()

    logger.info("Fetching activity list from Garmin Connect...")
    activities = []
    start, limit = 0, 1000

    # Paginate through activity list
    while True:
        batch = client.get_activities(start, limit)
        if not batch:
            break
        activities.extend(batch)
        if len(batch) < limit:
            break
        start += limit

    all_laps = []
    column_mapping = {
        "lapIndex": "lap_id",
        "avgGradeAdjustedSpeed": "grade_adjusted_speed",
        "averageHR": "averageHr",
        "distance": "distance",
        "duration": "duration",
    }
    required_keys = [
        "grade_adjusted_speed",
        "averageHr",
        "distance",
        "duration",
    ]

    for act in activities:
        activity_id = act.get("activityId")
        if not activity_id:
            continue
        start_time_local = act.get("startTimeLocal", "")

        try:
            splits_data = client.get_activity_splits(activity_id)
            splits_list = []

            if isinstance(splits_data, dict):
                for key in ["lapDTOs", "splits", "splitSummaries"]:
                    if key in splits_data:
                        splits_list = splits_data[key]
                        break
                if not splits_list:
                    splits_list = [splits_data]
            elif isinstance(splits_data, list):
                splits_list = splits_data

            if splits_list:
                df_laps = pd.DataFrame(splits_list)

                existing_cols = [
                    col
                    for col in column_mapping.keys()
                    if col in df_laps.columns
                ]
                mapped_cols = [column_mapping[col] for col in existing_cols]

                # Skip activity if it lacks required metrics
                if not all(req in mapped_cols for req in required_keys):
                    continue

                df_laps["run_id"] = activity_id
                df_laps["startTimeLocal"] = start_time_local

                selected_df = df_laps[
                    ["run_id", "startTimeLocal"] + existing_cols
                ].copy()
                selected_df.rename(columns=column_mapping, inplace=True)
                all_laps.append(selected_df)

        except Exception as e:
            logger.error(
                f"Failed to fetch splits for activity {activity_id}: {e}"
            )

    return pd.concat(all_laps, ignore_index=True) if all_laps else pd.DataFrame()


def calculate_run_quality(laps_df: pd.DataFrame) -> pd.DataFrame:
    """Computes lap difficulty, effort, and total run distance, aggregating

    results to calculate an overall 'quality' score per run (2026 onwards).
    """
    if laps_df.empty:
        return pd.DataFrame()

    df = laps_df.copy()

    required_cols = [
        "grade_adjusted_speed",
        "distance",
        "averageHr",
        "duration",
    ]
    for col in required_cols:
        if col not in df.columns:
            logger.warning(
                f"Missing required metric '{col}' for quality calculation."
            )
            return pd.DataFrame()
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # 1. Lap Difficulty = adjusted speed * distance
    df["difficulty"] = df["grade_adjusted_speed"] * df["distance"]

    # 2. Lap Effort = average heart rate * duration
    df["effort"] = df["averageHr"] * df["duration"]

    df = df.dropna(subset=["difficulty", "effort", "distance"])

    # 3. Sum difficulty, effort, and total distance across laps per run
    run_summary = (
        df.groupby(["run_id", "startTimeLocal"])
        .agg(
            total_difficulty=("difficulty", "sum"),
            total_effort=("effort", "sum"),
            total_distance_m=("distance", "sum"),
        )
        .reset_index()
    )

    # Run Quality = total difficulty / total effort
    run_summary["quality"] = (
        run_summary["total_difficulty"] / run_summary["total_effort"]
    )

    # Convert distance from meters to kilometers
    run_summary["total_distance_km"] = run_summary["total_distance_m"] / 1000.0

    # Parse date and filter strictly from Jan 1, 2026 onwards
    run_summary["run_date"] = pd.to_datetime(run_summary["startTimeLocal"])
    run_summary = run_summary[run_summary["run_date"] >= "2026-01-01"]

    return run_summary.sort_values("run_date").reset_index(drop=True)


def generate_and_save_plot(run_summary: pd.DataFrame, output_path: Path):
    """Generates subplots categorized by run distance ranges with 30-day rolling

    averages and legends.
    """
    clean_df = (
        run_summary.dropna(subset=["run_date", "quality", "total_distance_km"])
        .sort_values("run_date")
        .copy()
    )

    if clean_df.empty:
        logger.warning("No valid 2026 data available to generate plot.")
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Define distance range subplots
    bins = [
        ("< 6 km", lambda d: d < 6),
        ("6 - 8 km", lambda d: (d >= 6) & (d <= 8)),
        ("8 - 10 km", lambda d: (d > 8) & (d <= 10)),
        ("10 - 12 km", lambda d: (d > 10) & (d <= 12)),
        ("12 - 15 km", lambda d: (d > 12) & (d <= 15)),
        ("15+ km", lambda d: d > 15),
    ]

    fig, axes = plt.subplots(
        nrows=len(bins), ncols=1, figsize=(12, 18), sharex=True
    )

    for ax, (label, condition) in zip(axes, bins):
        subset = clean_df[condition(clean_df["total_distance_km"])].copy()

        if not subset.empty:
            # 30-day rolling average for this subplot
            subset_indexed = subset.set_index("run_date")
            rolling_30d = subset_indexed.rolling("30D")["quality"].mean()

            # Scatter plot
            ax.scatter(
                subset["run_date"],
                subset["quality"],
                color="#2b5c8f",
                alpha=0.6,
                label="Run Quality (Raw)",
                zorder=2,
            )

            # 30-Day Rolling Average Line
            ax.plot(
                rolling_30d.index,
                rolling_30d.values,
                color="#27ae60",
                linewidth=2,
                label="30-Day Rolling Avg",
                zorder=3,
            )
        else:
            ax.text(
                0.5,
                0.5,
                "No Data in Range",
                horizontalalignment="center",
                verticalalignment="center",
                transform=ax.transAxes,
                color="gray",
                fontsize=10,
            )

        ax.set_title(f"Distance Range: {label}", fontsize=11, fontweight="bold")
        ax.set_ylabel("Dahu Quality", fontsize=9)
        ax.grid(True, linestyle="--", alpha=0.5)
        ax.legend(loc="upper left", fontsize=8, frameon=True)

    axes[-1].set_xlabel("Run Date", fontsize=11)
    fig.suptitle(
        "Run Quality Over Time by Distance Category (2026+)",
        fontsize=14,
        fontweight="bold",
        y=0.995,
    )

    plt.gcf().autofmt_xdate()
    plt.tight_layout()

    plt.savefig(output_path, dpi=300)
    plt.close()
    logger.info(f"Plot saved successfully to {output_path}")


if __name__ == "__main__":
    combined_runs_df = get_combined_runs_dataset()

    if not combined_runs_df.empty:
        quality_df = calculate_run_quality(combined_runs_df)

        if not quality_df.empty:
            plot_output = Path("docs/public/images/running-plot-auto.png")
            generate_and_save_plot(quality_df, plot_output)
        else:
            logger.warning("Could not compute run quality from 2026 lap data.")
    else:
        logger.warning("No running data found.")