# ==============================================================================
# NOTE: THIS SCRIPT WAS GENERATED BY AN LLM (LARGE LANGUAGE MODEL).
# ==============================================================================

import os
import logging
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from garminconnect import (
    Garmin,
    GarminConnectAuthenticationError,
    GarminConnectTooManyRequestsError,
)

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)


def initialize_garmin_client() -> Garmin:
    """Initializes and authenticates the Garmin Connect API client."""
    token_store = Path.home() / ".garminconnect"

    try:
        logger.info(f"Attempting to login using stored tokens from {token_store}...")
        client = Garmin()
        client.login(token_store)
        return client
    except Exception:
        logger.info("Stored tokens invalid or not found. Falling back to environment variables...")

    email = os.getenv("GARMIN_EMAIL")
    password = os.getenv("GARMIN_PASSWORD")

    if not email or not password:
        raise ValueError("Missing GARMIN_EMAIL or GARMIN_PASSWORD environment variables.")

    client = Garmin(email=email, password=password)
    client.login(token_store)
    return client


def get_combined_trail_runs_dataset() -> pd.DataFrame:
    """Fetches trail running activity splits and extracts relevant lap metrics."""
    client = initialize_garmin_client()

    logger.info("Fetching activity list from Garmin Connect...")
    activities = []
    start, limit = 0, 1000

    # Paginate through activity list
    while True:
        batch = client.get_activities(start, limit)
        if not batch:
            break
        activities.extend(batch)
        if len(batch) < limit:
            break
        start += limit

    # Filter strictly for trail running
    trail_runs = [
        act for act in activities 
        if act.get("activityType", {}).get("typeKey", "").lower() == "trail_running"
    ]

    all_laps = []
    # Map Garmin API split keys to standardized pandas column names
    column_mapping = {
        "lapIndex": "lap_id",
        "avgGradeAdjustedSpeed": "grade_adjusted_speed",
        "averageHR": "averageHr",
        "distance": "distance",
        "duration": "duration",
    }

    for act in trail_runs:
        activity_id = act["activityId"]
        start_time_local = act.get("startTimeLocal", "")

        try:
            splits_data = client.get_activity_splits(activity_id)
            splits_list = []
            
            if isinstance(splits_data, dict):
                for key in ["lapDTOs", "splits", "splitSummaries"]:
                    if key in splits_data:
                        splits_list = splits_data[key]
                        break
                if not splits_list:
                    splits_list = [splits_data]
            elif isinstance(splits_data, list):
                splits_list = splits_data

            if splits_list:
                df_laps = pd.DataFrame(splits_list)
                df_laps["run_id"] = activity_id
                df_laps["startTimeLocal"] = start_time_local

                # Retain only relevant present columns and rename
                existing_cols = [col for col in column_mapping.keys() if col in df_laps.columns]
                selected_df = df_laps[["run_id", "startTimeLocal"] + existing_cols].copy()
                selected_df.rename(columns=column_mapping, inplace=True)
                all_laps.append(selected_df)

        except Exception as e:
            logger.error(f"Failed to fetch splits for activity {activity_id}: {e}")

    return pd.concat(all_laps, ignore_index=True) if all_laps else pd.DataFrame()


def calculate_run_quality(laps_df: pd.DataFrame) -> pd.DataFrame:
    """
    Computes lap difficulty and effort without loops, aggregating results to 
    calculate a overall 'quality' score per run.
    """
    if laps_df.empty:
        return pd.DataFrame()

    df = laps_df.copy()

    # Ensure required metrics exist and are numeric
    required_cols = ["grade_adjusted_speed", "distance", "averageHr", "duration"]
    for col in required_cols:
        if col not in df.columns:
            logger.warning(f"Missing required metric '{col}' for quality calculation.")
            return pd.DataFrame()
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # 1. Lap Difficulty = adjusted speed * distance
    df["difficulty"] = df["grade_adjusted_speed"] * df["distance"]

    # 2. Lap Effort = average heart rate * duration
    df["effort"] = df["averageHr"] * df["duration"]

    # Remove incomplete lap records
    df = df.dropna(subset=["difficulty", "effort"])

    # 3. Sum difficulty and effort across laps per run using vectorized aggregation
    run_summary = df.groupby(["run_id", "startTimeLocal"]).agg(
        total_difficulty=("difficulty", "sum"),
        total_effort=("effort", "sum")
    ).reset_index()

    # Run Quality = total difficulty / total effort
    run_summary["quality"] = run_summary["total_difficulty"] / run_summary["total_effort"]

    # Parse and sort chronologically by date
    run_summary["run_date"] = pd.to_datetime(run_summary["startTimeLocal"])
    return run_summary.sort_values("run_date").reset_index(drop=True)




def generate_and_save_plot(run_summary: pd.DataFrame, output_path: Path):
    """Generates and saves a time-series plot of run quality with rolling averages,

    a linear regression trend line, and a legend.
    """
    clean_df = (
        run_summary.dropna(subset=["run_date", "quality"])
        .sort_values("run_date")
        .copy()
    )

    if clean_df.empty:
        logger.warning("No valid data available to generate plot.")
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)

    # --- 1. Calculate Rolling Averages ---
    # Using time-based windows ('7D' and '30D') on date-indexed data
    df_indexed = clean_df.set_index("run_date")
    clean_df["rolling_7d"] = df_indexed.rolling("7D")["quality"].mean().values
    clean_df["rolling_30d"] = (
        df_indexed.rolling("30D")["quality"].mean().values
    )

    # --- 2. Calculate Linear Regression Trend Line ---
    # Convert dates to ordinal numbers for linear regression fitting
    x_ordinal = clean_df["run_date"].map(pd.Timestamp.toordinal)
    y_quality = clean_df["quality"]

    # Calculate slope and intercept using numpy polyfit
    slope, intercept = np.polyfit(x_ordinal, y_quality, 1)
    linear_trend = slope * x_ordinal + intercept

    # --- 3. Plotting ---
    plt.figure(figsize=(12, 6))

    # Scatter plot of raw quality points
    plt.scatter(
        clean_df["run_date"],
        clean_df["quality"],
        color="#2b5c8f",
        alpha=0.5,
        label="Run Quality (Raw)",
        zorder=2,
    )

    # 7-Day Rolling Average
    plt.plot(
        clean_df["run_date"],
        clean_df["rolling_7d"],
        color="#f39c12",
        linewidth=2,
        label="7-Day Rolling Avg",
        zorder=3,
    )

    # 30-Day Rolling Average
    plt.plot(
        clean_df["run_date"],
        clean_df["rolling_30d"],
        color="#27ae60",
        linewidth=2,
        label="30-Day Rolling Avg",
        zorder=4,
    )

    # Linear Regression Line
    plt.plot(
        clean_df["run_date"],
        linear_trend,
        color="#c0392b",
        linestyle="--",
        linewidth=2,
        label="Linear Trend",
        zorder=5,
    )

    # Aesthetics & Legend
    plt.title("Trail Run Quality Over Time", fontsize=14, fontweight="bold")
    plt.xlabel("Run Date", fontsize=11)
    plt.ylabel("Dahu Quality", fontsize=11)
    plt.grid(True, linestyle="--", alpha=0.5)
    plt.legend(loc="upper left", frameon=True)

    plt.gcf().autofmt_xdate()
    plt.tight_layout()

    plt.savefig(output_path, dpi=300)
    plt.close()
    logger.info(f"Plot saved successfully to {output_path}")


if __name__ == "__main__":
    combined_trail_df = get_combined_trail_runs_dataset()

    if not combined_trail_df.empty:
        quality_df = calculate_run_quality(combined_trail_df)
        
        if not quality_df.empty:
            plot_output = Path("docs/public/images/running-plot-auto.png")
            generate_and_save_plot(quality_df, plot_output)
        else:
            logger.warning("Could not compute run quality from lap data.")
    else:
        logger.warning("No trail running data found.")